version: 2

project_name: sercha

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    main: ./cmd/sercha/main.go
    binary: sercha
    goos: [linux]
    goarch: [amd64]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

  - id: linux-arm64
    main: ./cmd/sercha/main.go
    binary: sercha
    goos: [linux]
    goarch: [arm64]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

  - id: darwin-amd64
    main: ./cmd/sercha/main.go
    binary: sercha
    goos: [darwin]
    goarch: [amd64]
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

  - id: darwin-arm64
    main: ./cmd/sercha/main.go
    binary: sercha
    goos: [darwin]
    goarch: [arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: sercha
    repository:
      owner: custodia-labs
      name: homebrew-sercha
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    commit_author:
      name: "Sercha Bot"
      email: "gurushey.deo@custodialabs.com"
    description: "Sercha CLI"
    homepage: "https://github.com/custodia-labs/sercha-cli"
    binaries:
      - sercha

nfpms:
  - id: deb_pkgs
    package_name: sercha
    maintainer: "Gurushey Deo <gurushey.deo@custodialabs.com>"
    description: "Sercha CLI"
    homepage: "https://github.com/custodia-labs/sercha-cli"
    license: MIT
    formats: [deb]
    bindir: /usr/bin

  - id: rpm_pkgs
    package_name: sercha
    maintainer: "Gurushey Deo <gurushey.deo@custodialabs.com>"
    description: "Sercha CLI"
    homepage: "https://github.com/custodia-labs/sercha-cli"
    license: MIT
    formats: [rpm]
    bindir: /usr/bin

publishers:
  - name: upload-deb-jammy
    ids: [deb_pkgs]
    cmd: cloudsmith push deb custodia-labs/sercha/ubuntu/jammy {{ .ArtifactPath }}
    env:
      - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}

  - name: upload-deb-noble
    ids: [deb_pkgs]
    cmd: cloudsmith push deb custodia-labs/sercha/ubuntu/noble {{ .ArtifactPath }}
    env:
      - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}

  - name: upload-rpm-to-cloudsmith
    ids: [rpm_pkgs]
    cmd: cloudsmith push rpm custodia-labs/sercha/el/9 {{ .ArtifactPath }}
    env:
      - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: custodia-labs
    name: sercha-cli
